## Exercise 9
### Exam STAT 210 Sep 2012, Exercise 1
**Question:** The purpose of this exercise to determine if a new diet treatment or method (called ’M1’) designed to help people loosing weight is better than two well known methods (called ’M2’ and ’M3’). Two individuals were recruited in each group. The individuals were weighed at the beginning and the end of the study. For each individual the weight difference (’final weight’-’initial weight’) was recorded. The data and some summary statistics are as follows:

```{r}
suppressMessages(library(data.table, quietly = TRUE, warn.conflicts = FALSE))
dta.raw <- data.table(Treatment = c('M1', 'M2', 'M3'),
                  Observations = I(list(c(0, 2), c(1, 3), c(5, 7))))
dta.raw[, Averages := lapply(Observations, mean)]
knitr::kable(dta.raw)
knitr::kable(cbind("Total Average", "", mean(unlist(dta.raw$Observations))))
```

We will use the model,

$$y_{ij} = \mu + \tau_i + \epsilon_{ij},\; \epsilon_{ij} \sim NID(0, \sigma^2)$$

Here,

$$
\begin{aligned}
i & = 1, 2, 3 \text{ corresponding to M1, M2 and M3} \\
j & = 1, 2 \text{ corresponding to the two observations in each treatment group} \\
y_{ij} & = \text{Weight Loss and}
\sum_{i = 1}^3{\tau_i} = 0
\end{aligned}
$$

a) Calculate $\text{SS}_\text{Treatment}$ and $\text{SS}_\text{E}$ defined below:

$$
\begin{aligned}
\text{SS}_\text{Treatment} &= 2\sum_{i = 1}^3 \left({\bar{y}_{i\cdot} - \bar{y}_{\cdot\cdot}}\right)^2 \\
\text{SS}_\text{E} &= \sum_{i = 1}^3\sum_{j = 1}^2\left(y_{ij} - \bar{y}_{i\cdot} \right)^2
\end{aligned}
$$

b) Consider the null hypothesis

$$H_0 : \tau_1 = \tau_2 = \tau_3 = 0$$

Show that the test statistic is $F_0=7$ and use this to perform the test. Formulate a conclusion.

c) We would like to extend on the above pilot study and design a real study. How would you design this study? You are free to state your assumptions. You _can_ mention words like _randomization_, _blocking_ and _replication_. You are not supposed to write more than 10 full sentences.
